#layout: site
title: Petrov's farm
email: lilipetrova75@abv.bg
description: The best food for your table!
baseurl: "/Petrov-s-farm" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
destination: "docs"
#twitter_username: jekyllrb
github_username:  LiliaPetrova

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
 exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - .gitignore
   - scss
   - gulpfile.js
   - package.json
   - package-lock.json
   - .vscode
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
