# Site settings
title: Petrov's farm
description: The best food for your table!

email: lilipetrova75@abv.bg
baseurl: "/Petrov-s-farm" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: LiliaPetrova
github_username:  LiliaPetrova

# Build settings
future: true
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

destination: docs

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - docs
  - scss
  - gulpfile.js
  - package.json
